prometheus:
  # Enable or disable Prometheus monitoring
  enable: true
  # autoSetPorts indicates whether to automatically set the ports
  autoSetPorts: true
  # List of ports that Prometheus listens on; each port corresponds to an instance of monitoring. Ensure these are managed accordingly
  # It will only take effect when autoSetPorts is set to false.
  ports:

ratelimiter:
  # Whether to enable rate limiting
  enable: true
  # WindowSize defines time duration per window
  window: 10s
  # BucketNum defines bucket number for each window
  bucket: 100
  # CPU threshold; valid range 0–1000 (1000 = 100%)
  cpuThreshold: 800

circuitBreaker:
  enable: true
  window: 3s            # Time window size (seconds)
  bucket: 10            # Number of buckets
  success: 0.6          # Success rate threshold (0.6 means 60%)
  requestThreshold: 100 # Request threshold; circuit breaker evaluation occurs when reached